apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-ai-services/ai-accelerator/components/operators/gpu-operator-certified/instance/overlays/aws?ref=main
